[package]
name = "juniper-eager-loading"
version = "0.0.1"
authors = ["David Pedersen <david.pdrsn@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Reserved for future use"

[dependencies]
